export const inspectionScope = [
  {
    id: "site-and-drainage",
    title: "Site, grounds, grading, and drainage",
    summary: "Visible site conditions can help explain how water and access affect the structure.",
    reviewed: [
      "Visible grading and drainage patterns near the structure",
      "Driveways, walkways, steps, patios, and visible hardscape",
      "Retaining walls and site structures within the agreed scope",
      "Vegetation contact, gates, fences, and exterior stairs when included",
      "Visible ponding, erosion, or moisture pathways toward the building",
    ],
    limitation: "The inspection does not include surveying, soil or geotechnical analysis, underground drainage mapping, irrigation performance unless agreed, or prediction of flooding.",
  },
  {
    id: "exterior",
    title: "Exterior walls, trim, doors, and windows",
    summary: "Exterior finishes and openings are reviewed from safe, visible vantage points.",
    reviewed: [
      "Visible stucco, siding, brick veneer, trim, doors, and windows",
      "Penetrations, flashing details, sealant conditions, and openings",
      "Accessible decks, balconies, porches, guards, and handrails",
      "Eaves, soffits, fascia, and exterior-mounted components",
      "Visible deterioration, impact damage, moisture staining, or movement",
    ],
    limitation: "Paint and finish matching, concealed weather barriers, destructive moisture testing, and engineering analysis are outside a standard visual inspection.",
  },
  {
    id: "roof",
    title: "Roof covering and drainage",
    summary: "The roof is observed by the safest practical method available on the inspection day.",
    reviewed: [
      "Visible roof materials, flashings, penetrations, valleys, and transitions",
      "Gutters, downspouts, and visible discharge points",
      "Signs of damage, wear, repair, or possible leakage",
      "Roof-mounted equipment, skylights, and drainage details within scope",
    ],
    limitation: "Access depends on height, material, slope, weather, condition, and safety. This is not a roof certification or leak guarantee.",
  },
  {
    id: "structure",
    title: "Structure and foundation",
    summary: "Visible support components and related conditions are documented without engineering calculations.",
    reviewed: [
      "Visible foundation walls, slabs, piers, posts, beams, and framing",
      "Observable cracking, displacement, deterioration, or moisture effects",
      "Visible floor and wall conditions that may warrant further evaluation",
      "Accessible support connections and framing components",
    ],
    limitation: "The inspection does not calculate loads, determine structural adequacy, design repairs, certify seismic performance, or provide engineering analysis.",
  },
  {
    id: "crawlspace",
    title: "Crawlspace or under-floor area",
    summary: "Safely accessible under-floor areas can provide important structural and moisture context.",
    reviewed: [
      "Foundation, framing, posts, beams, joists, and subfloor",
      "Ventilation and visible moisture conditions",
      "Visible plumbing, electrical, duct, and insulation components",
      "Standing water, leakage, deterioration, or restricted access",
    ],
    limitation: "Entry depends on opening size, clearance, water, animals, debris, suspected hazards, and other safety conditions. Unsafe areas are reported as limitations.",
  },
  {
    id: "attic",
    title: "Attic, roof structure, insulation, and ventilation",
    summary: "Visible attic conditions are reviewed where entry and movement are reasonably safe.",
    reviewed: [
      "Rafters, trusses, sheathing, and visible framing",
      "Leakage, staining, deterioration, or repair evidence",
      "Visible insulation distribution and obvious gaps",
      "Ventilation, ducts, exhaust terminations, and accessible electrical components",
    ],
    limitation: "The inspector does not disturb insulation, enter unsafe areas, or determine hidden damage, exact R-values, air leakage, or indoor-air quality unless separately agreed and supported.",
  },
  {
    id: "electrical",
    title: "Electrical system",
    summary: "Readily accessible electrical equipment and representative controls are observed for visible concerns.",
    reviewed: [
      "Service entrance, main equipment, and accessible subpanels",
      "Overcurrent devices, visible conductors, grounding, and bonding observations",
      "Representative outlets, switches, lighting, and accessible GFCI/AFCI protection",
      "Smoke and carbon-monoxide alarm presence where within scope",
    ],
    limitation: "This is not an electrical-code certification, load calculation, exhaustive circuit trace, solar-production test, or concealed-wiring evaluation.",
  },
  {
    id: "plumbing",
    title: "Plumbing and water distribution",
    summary: "Visible supply, drainage, fixtures, and accessible connections are reviewed under normal controls.",
    reviewed: [
      "Visible supply and drain piping, fixtures, faucets, toilets, tubs, and showers",
      "Functional flow and drainage observations at operated fixtures",
      "Visible shutoff valves, cleanouts, leakage, corrosion, and damage",
      "Sump equipment only when present, accessible, and included",
    ],
    limitation: "Sewer scoping, septic evaluation, water-quality testing, concealed or underground piping, destructive leak detection, and guaranteed pressure are not included unless separately agreed.",
  },
  {
    id: "gas",
    title: "Visible gas distribution",
    summary: "Accessible gas equipment and piping receive a limited visual review.",
    reviewed: [
      "Visible meter location, piping, supports, and obvious damage",
      "Accessible appliance shutoffs and connector observations",
      "Visible corrugated stainless steel tubing observations where applicable",
    ],
    limitation: "A standard inspection is not a comprehensive gas-leak test, pressure test, utility clearance, or engineering determination. Suspected leakage requires immediate qualified action.",
  },
  {
    id: "water-heater",
    title: "Water heater",
    summary: "Visible water-heating equipment is observed for installation context and apparent condition.",
    reviewed: [
      "Visible type, fuel, location, venting, and general condition",
      "Temperature and pressure relief components and visible discharge piping",
      "Seismic restraint, drain pan, and drainage provisions where present",
      "Visible leakage, corrosion, damage, and accessible labels",
    ],
    limitation: "Age is reported only when supported by accessible manufacturer data. Remaining life, internal tank condition, water quality, and future leakage cannot be guaranteed.",
  },
  {
    id: "heating",
    title: "Heating system",
    summary: "Installed heating equipment is operated with normal controls when conditions permit.",
    reviewed: [
      "Accessible equipment, controls, filters, and operating response",
      "Visible fuel, electrical, venting, condensate, distribution, and duct components",
      "Damage, unusual operation, or indications that service may be useful",
    ],
    limitation: "The inspection is not a combustion analysis, heat-exchanger certification, duct-leakage test, energy audit, or complete HVAC service.",
  },
  {
    id: "cooling",
    title: "Cooling system",
    summary: "Installed cooling equipment is operated only when weather and observed conditions allow safe use.",
    reviewed: [
      "Accessible equipment, thermostat controls, and normal operating response",
      "Visible refrigerant lines, condensate routing, disconnects, and equipment condition",
      "Accessible distribution components and visible ductwork",
    ],
    limitation: "Refrigerant charge, internal components, efficiency, and remaining life require specialist evaluation. Equipment may not be operated when doing so could cause damage.",
  },
  {
    id: "kitchen",
    title: "Kitchen",
    summary: "Kitchen finishes, plumbing, protection, ventilation, and agreed built-in appliances are reviewed visibly.",
    reviewed: [
      "Counters, cabinets, sink, faucet, and visible plumbing",
      "Accessible GFCI protection and installed cooking ventilation",
      "Built-in appliances included by the agreement using normal controls",
      "Visible walls, ceilings, floors, doors, windows, leakage, and damage",
    ],
    limitation: "Appliance operation is a basic functional check, not a performance guarantee. Portable appliances, cosmetic wear, and recall research are outside scope unless stated.",
  },
  {
    id: "bathrooms",
    title: "Bathrooms",
    summary: "Accessible fixtures, finishes, ventilation, and visible water effects are reviewed.",
    reviewed: [
      "Sinks, faucets, toilets, tubs, showers, and visible plumbing",
      "Accessible GFCI protection, ventilation, and operable windows",
      "Visible walls, ceilings, floors, cabinets, and enclosures",
      "Functional drainage, visible leakage, guards, glazing, and safety conditions",
    ],
    limitation: "Concealed waterproofing, hidden leaks, mold testing, destructive probing, and finish or sealant guarantees are not part of a standard inspection.",
  },
  {
    id: "laundry",
    title: "Laundry area",
    summary: "Visible laundry connections and related room conditions are reviewed without moving connected equipment.",
    reviewed: [
      "Visible supply, drain, gas, and electrical connections",
      "Dryer exhaust routing where visible",
      "Accessible GFCI protection, ventilation, flooring, and leakage conditions",
      "Installed equipment only when included in the agreement",
    ],
    limitation: "The inspector does not move connected appliances or verify concealed dryer ducts and plumbing.",
  },
  {
    id: "interior",
    title: "Bedrooms and interior rooms",
    summary: "Interior rooms are reviewed for visible condition, access, and common safety observations.",
    reviewed: [
      "Visible walls, ceilings, floors, doors, and representative windows",
      "Stairs, guards, handrails, and walking surfaces",
      "Accessible outlets, switches, lighting, and alarms",
      "Signs of moisture, deterioration, movement, and access limitations",
    ],
    limitation: "Furniture, belongings, coverings, and finishes can conceal conditions. Cosmetic judgments and legal room-classification measurements are not included unless stated.",
  },
  {
    id: "garage",
    title: "Garage and carport",
    summary: "Accessible garage and carport conditions are reviewed using safe operating methods.",
    reviewed: [
      "Walls, ceilings, floors, framing, and visible separation from living areas",
      "Vehicle doors, openers, and accessible safety-reversal features",
      "Service doors, windows, electrical components, and fuel-burning equipment",
      "Visible damage, moisture, unsafe conditions, and access limitations",
    ],
    limitation: "Door testing depends on safe operation and current conditions. Fire-resistance observations are visual and are not a code certification.",
  },
  {
    id: "fireplace",
    title: "Fireplace and chimney",
    summary: "Readily visible fireplace and chimney components are observed for apparent concerns.",
    reviewed: [
      "Visible firebox, damper, hearth, facing, and accessible chimney components",
      "Obvious damage, deterioration, clearance concerns, or prior leakage",
      "Installed gas components where visible and within scope",
    ],
    limitation: "This is not a Level 2 chimney inspection, flue scan, cleaning, draft analysis, or certification for use. Specialist evaluation may be recommended before operation.",
  },
  {
    id: "pool-spa",
    title: "Optional pool and spa service",
    summary: "This optional service is not currently approved for publication.",
    reviewed: [],
    limitation: "Owner approval, qualifications, agreement, report support, pricing, and current California reporting requirements are still required.",
    enabled: false,
  },
  {
    id: "outside-scope",
    title: "Items commonly outside a standard inspection",
    summary: "Some questions require a different service, qualification, test, or level of access.",
    reviewed: [
      "Concealed conditions, destructive testing, and opening finishes or equipment",
      "Code certification, permit research, appraisal, market value, or insurability",
      "Engineering, architecture, geology, environmental, mold, asbestos, lead, radon, air, water, or hazardous-material testing",
      "Pest/WDO, sewer, septic, well, irrigation, solar-production, security, low-voltage, recall, and warranty research unless separately agreed",
      "Prediction of remaining life, future failure, repair design, contractor bids, or cost estimates",
    ],
    limitation: "The signed agreement and property-specific conditions control the final scope. Appropriate specialist evaluation may be recommended when a question falls outside it.",
  },
];

export const enabledInspectionScope = inspectionScope.filter((section) => section.enabled !== false);
