const educationalDisclaimer =
  "This guide is general education. It does not replace the signed inspection agreement, a property-specific inspection or report, or advice from an appropriately licensed or qualified professional.";

const article = (value) => ({
  author: "C&G Certified Home Inspector",
  published: "2026-07-22",
  modified: "2026-07-22",
  disclaimer: educationalDisclaimer,
  ...value,
});

export const resourceArticles = [
  article({
    slug: "preparing-for-a-home-inspection",
    category: "Before the inspection",
    title: "Preparing for a Home Inspection",
    summary: "Reduce preventable access limitations before the inspector arrives. A few practical preparations help the visit begin with the systems and questions that matter.",
    intro: "Preparation is not about making a property look perfect. It is about creating safe, authorized access and sharing useful context so the inspector can document what is visible on the inspection day.",
    sections: [
      { heading: "Confirm the appointment, access, and utilities", body: "Confirm the agreed date, arrival instructions, occupancy conditions, and authorized access. Utilities should be on only when safe and permitted; the inspector will not activate a shut-down service or operate a system without appropriate authorization." },
      { heading: "Make major systems reachable", body: "Clear reasonable working space around the electrical panel, water heater, heating and cooling equipment, attic opening, crawlspace opening, and other systems included in the agreement. The inspector does not move heavy furniture, appliances, storage, or personal belongings." },
      { heading: "Unlock the agreed areas", body: "Arrange keys or access for garages, gates, utility rooms, detached structures, roof access points, and other included areas. Do not share alarm codes or lockbox information through an ordinary website form." },
      { heading: "Plan for pets and occupancy", body: "Secure pets and explain any occupancy, tenant, child, or work-from-home conditions that could affect safe movement. The parties coordinating access should resolve transaction rules before the appointment." },
      { heading: "Gather context without expecting a document audit", body: "Known repair records, warranties, or a short question list may help the conversation. A standard inspection does not verify every document, permit, disclosure, or warranty, and the inspector should not be expected to decide whether a transaction should proceed." },
      { heading: "Avoid rushed cover-ups", body: "Do not conceal a condition or make a cosmetic change merely to hide visible evidence. If a repair was recently performed, make the area reasonably accessible and share accurate context when appropriate." },
      { heading: "Understand what will not be moved", body: "Furniture, connected appliances, floor coverings, stored belongings, finishes, and insulation may conceal conditions. Those limitations belong in the report when they materially affect the inspection." },
      { heading: "If an important area is inaccessible", body: "The report should identify the limitation. Depending on the property and transaction, the client may discuss a separately agreed return visit or evaluation by an appropriate specialist." },
    ],
    checklist: ["Utilities on and safe to operate", "Keys and access arranged", "Major systems reachable", "Pets secured", "Client questions collected", "Property details sent"],
    takeaway: "Safe access and accurate property context are more useful than cosmetic preparation.",
    related: ["visible-and-accessible-conditions", "questions-to-ask-your-inspector", "how-to-read-a-home-inspection-report"],
    cta: { label: "Review the Full Inspection Scope", path: "/services/" },
  }),
  article({
    slug: "how-to-read-a-home-inspection-report",
    category: "Understanding the report",
    title: "How to Read a Home Inspection Report",
    summary: "A report is more useful when you read beyond the summary. Follow each observation through its location, context, limitation, and recommended next step.",
    intro: "The report is a property-specific record of visible conditions at one point in time. It should help you locate an observation, understand why it was recorded, and identify the right follow-up question.",
    sections: [
      { heading: "Read the entire report", body: "A summary can help with navigation, but it cannot carry every photograph, limitation, maintenance note, or system-specific explanation. Start with the full report before turning findings into a repair list." },
      { heading: "Separate observation, context, and recommendation", body: "An observation records what was visible. Context explains why it may matter or what remains uncertain. A recommendation identifies the next useful action, which may be monitoring, maintenance, repair, or specialist evaluation." },
      { heading: "Confirm the location and system", body: "Similar conditions can mean different things in different places. Use room names, exterior elevations, equipment labels, photographs, and surrounding system information to make sure everyone is discussing the same item." },
      { heading: "Distinguish material concerns from maintenance", body: "Safety-related and material conditions deserve careful attention, but routine maintenance also matters. The report should not turn every observation into the same level of alarm." },
      { heading: "Read the limitations", body: "A locked room, stored belongings, unsafe roof, shut-down utility, or inaccessible crawlspace changes what could be observed. A limitation is important report content, not fine print to skip." },
      { heading: "Recognize specialist recommendations", body: "When an observation needs engineering, electrical, plumbing, roofing, HVAC, pest, environmental, or other focused expertise, obtain that evaluation from an appropriately qualified provider." },
      { heading: "Ask the inspector for clarification", body: "Use the report section, page, location, and photograph when asking a question. The inspector can explain the recorded observation and recommendation without making the purchase decision for you." },
      { heading: "Use independent estimates and advisers", body: "Transaction choices, legal disclosures, financing, insurance, and repair pricing belong with the appropriate advisers and independent providers. C&G contracting work is prohibited on a property C&G inspected during the previous 12 months." },
    ],
    takeaway: "Read for location, evidence, limitation, and next step—not just a count of findings.",
    related: ["what-to-do-after-the-inspection", "visible-and-accessible-conditions", "home-inspection-vs-appraisal"],
    cta: { label: "Explore Report Expectations", path: "/services/" },
  }),
  article({
    slug: "home-inspection-vs-appraisal",
    category: "Understanding the report",
    title: "Home Inspection vs. Appraisal",
    summary: "An inspection and an appraisal answer different questions. Understanding those roles prevents a value opinion from being mistaken for a condition review—or the reverse.",
    intro: "Both services may appear in a real-estate transaction, but they are not substitutes. The provider, client, scope, methods, and resulting report differ.",
    sections: [
      { heading: "Different purposes", body: "A home inspection focuses on visible and accessible property conditions under a signed agreement. An appraisal is generally concerned with an opinion of value for its intended use and client." },
      { heading: "Condition focus versus value focus", body: "An inspector documents observable systems, components, limitations, and recommended follow-up. An appraiser considers the information required by the appraisal assignment; that work is not a system-by-system home inspection." },
      { heading: "Who orders each service", body: "The party engaging an inspector is the inspection client. An appraisal may be ordered for a lender or another identified client. Report access, reliance, and confidentiality follow the relevant engagement." },
      { heading: "Why one does not replace the other", body: "A favorable appraisal does not establish that the roof, structure, plumbing, electrical, HVAC, or other systems were inspected. An inspection does not determine market value or satisfy appraisal requirements." },
      { heading: "Other evaluations are different too", body: "Lender, insurance, pest, code, environmental, sewer, engineering, and specialty-trade evaluations each have different purposes. Ask who is performing the service, for whom, and under what written scope." },
      { heading: "Questions before assuming coverage", body: "Confirm what will be reviewed, what will not, what report will be delivered, how limitations are handled, and whether additional providers may be needed for the property or transaction." },
    ],
    takeaway: "Inspection explains visible condition; appraisal addresses value for a defined assignment.",
    related: ["questions-to-ask-your-inspector", "how-to-read-a-home-inspection-report", "what-to-do-after-the-inspection"],
    cta: { label: "See What an Inspection Covers", path: "/services/" },
  }),
  article({
    slug: "visible-and-accessible-conditions",
    category: "Understanding the report",
    title: "What “Visible and Accessible” Means",
    summary: "A home inspection is visual and non-invasive. Access, safety, storage, finishes, weather, and property conditions determine what can be observed on the inspection day.",
    intro: "The phrase visible and accessible sets an honest boundary. It does not mean the inspector ignores difficult areas; it means the service does not promise knowledge of conditions that cannot be seen or reached safely.",
    sections: [
      { heading: "The non-invasive inspection model", body: "The inspector observes accessible surfaces, systems, and components and uses normal controls where appropriate. Walls, floors, ceilings, equipment housings, and finishes are not opened or damaged to search for concealed conditions." },
      { heading: "Common barriers", body: "Furniture, floor coverings, stored materials, locked doors, insulation, water, debris, vegetation, animals, and personal belongings can block access. The inspector does not move heavy or unsafe items to create a view." },
      { heading: "Roofs, attics, and crawlspaces", body: "Height, slope, roof material, weather, opening size, clearance, standing water, suspected hazards, damaged framing, and other conditions can limit entry. A safer vantage point may be used." },
      { heading: "Concealed conditions cannot be ruled out", body: "A dry visible surface does not prove that every concealed area is dry. A functional control does not guarantee future performance. The report should avoid certainty beyond the evidence available." },
      { heading: "How limitations appear in the report", body: "A useful limitation identifies the area or system, the reason it was not fully observed or operated, and any appropriate recommendation. Significant limitations should be easy to find." },
      { heading: "Return visits and specialists", body: "If access later changes or a focused question remains, the client can discuss a separately agreed return visit or evaluation by the appropriate specialist. That decision depends on the property and the importance of the missing information." },
    ],
    takeaway: "A limitation is part of the inspection result and should be read with the same care as a finding.",
    related: ["preparing-for-a-home-inspection", "how-to-read-a-home-inspection-report", "questions-to-ask-your-inspector"],
    cta: { label: "Review Scope and Limitations", path: "/services/" },
  }),
  article({
    slug: "questions-to-ask-your-inspector",
    category: "Before the inspection",
    title: "Questions to Ask Your Home Inspector",
    summary: "Good questions reveal how an inspector defines scope, documents limitations, communicates findings, and manages conflicts. Ask before relying on a credential, timing promise, or optional service.",
    intro: "Choosing an inspector is not only about a price or an available time. It is also about the written scope, report quality, independence, and whether the provider can explain what the service will and will not answer.",
    sections: [
      { heading: "What controls the scope?", body: "Ask which agreement and standard of practice define the inspection. Request a chance to review the agreement before the appointment rather than discovering major exclusions after the visit." },
      { heading: "What property types and optional services are supported?", body: "A provider should distinguish ordinary residential scope from a special property type or optional system. Confirm that the agreement and report support any added service." },
      { heading: "How are limitations documented?", body: "Ask how inaccessible, unsafe, shut-down, or excluded areas appear in the report and what options exist if an important area later becomes accessible." },
      { heading: "What does the report look like?", body: "A sample may help when it is real, current, redacted, and approved. Look for clear locations, photographs, limitations, and recommendations—not only a short summary." },
      { heading: "What follow-up is available?", body: "Confirm how report questions are handled and whether a separately priced return visit may be available when conditions change. Do not assume unlimited consulting or reinspection is included." },
      { heading: "How are conflicts handled?", body: "Ask whether findings create any financial interest in repair work. C&G keeps inspection and contracting separate and cannot offer or perform repairs on a property it inspected during the previous 12 months." },
      { heading: "Can credentials and insurance statements be verified?", body: "Request current evidence and exact public wording rather than relying on an unsupported badge or broad claim. The relevant organization or insurer should be identifiable where appropriate." },
      { heading: "What are the expected timing and price?", body: "Confirm the quote, payment expectations, appointment window, report-delivery expectation, and factors that could change them. A website request is not an appointment until accepted." },
    ],
    takeaway: "Ask for the written scope and evidence behind important claims before relying on them.",
    related: ["preparing-for-a-home-inspection", "home-inspection-vs-appraisal", "visible-and-accessible-conditions"],
    cta: { label: "Ask C&G About a Property", path: "/contact/" },
  }),
  article({
    slug: "pre-listing-inspection-guide",
    category: "Before the inspection",
    title: "Pre-Listing Inspection Guide",
    summary: "A seller may use a pre-listing inspection to understand visible conditions before marketing a property. The report does not guarantee what another inspector will find or decide what must be disclosed or repaired.",
    intro: "A pre-listing inspection can support planning when the seller understands the service's limits and coordinates legal, disclosure, and repair decisions with the appropriate advisers.",
    sections: [
      { heading: "Why a seller may choose an inspection", body: "The inspection can create a current record of visible and accessible conditions and identify questions that may deserve evaluation before listing. It cannot control another party's inspection or transaction decisions." },
      { heading: "Prepare access and context", body: "Arrange safe access to major systems, keep utilities on when authorized, secure pets, and gather relevant repair context. Avoid cosmetic cover-ups that obscure visible evidence." },
      { heading: "Expect different observations later", body: "Conditions change, access differs, agreements vary, and another inspector may observe something different. A pre-listing report is not a guarantee that no additional issue will be raised." },
      { heading: "Decide on repairs with independent advice", body: "A seller may repair, monitor, disclose, investigate, or leave a condition for negotiation after consulting the appropriate professionals. The inspector does not make that transaction decision." },
      { heading: "Handle disclosures with the right adviser", body: "Legal disclosure duties and real-estate strategy require advice from the appropriate legal and transaction professionals. The inspection report is information, not legal advice." },
      { heading: "Share the report intentionally", body: "Understand who may receive and rely on the report under the agreement. Remove sensitive information when appropriate and do not assume a report can be repurposed without permission." },
      { heading: "Update the conversation when conditions change", body: "A leak, repair, vacancy, storm, utility change, or other event after the inspection can make part of the report outdated. Record material changes and obtain appropriate follow-up." },
    ],
    takeaway: "A pre-listing inspection supports planning; it does not guarantee a result or replace disclosure advice.",
    related: ["preparing-for-a-home-inspection", "how-to-read-a-home-inspection-report", "what-to-do-after-the-inspection"],
    cta: { label: "Discuss an Inspection Request", path: "/contact/" },
  }),
  article({
    slug: "drainage-and-grading-basics",
    category: "Systems and maintenance context",
    title: "Drainage and Grading Basics",
    summary: "Visible water pathways around a home can connect roof runoff, hardscape, grading, and below-floor moisture. A standard inspection observes accessible conditions but is not a drainage-engineering or flood study.",
    intro: "Water tends to follow available paths. Looking at the site and exterior together can help explain why a low area, disconnected downspout, or surface slope deserves attention.",
    sections: [
      { heading: "Why water movement matters", body: "Repeated water near a structure can affect finishes, soil, foundations, crawlspaces, and interior conditions. One observation rarely proves the entire source or repair design." },
      { heading: "Roof runoff and downspouts", body: "Roof coverings, gutters, downspouts, discharge points, and visible splash patterns can provide useful context. Weather and access affect what can be observed on the inspection day." },
      { heading: "Visible grading and low areas", body: "Surface slopes, depressions, erosion, ponding evidence, and soil contact may suggest where water collects or travels. The inspector does not perform a survey or calculate drainage capacity." },
      { heading: "Hardscape and vegetation", body: "Walkways, patios, planters, retaining elements, and vegetation can change visible water pathways or conceal portions of the site and exterior." },
      { heading: "Related crawlspace or interior observations", body: "Moisture staining, efflorescence, damp soil, deterioration, or odor may deserve follow-up, but the visible condition does not by itself establish every concealed cause." },
      { heading: "What the inspection is not", body: "The service is not a flood determination, soil analysis, geotechnical study, irrigation test, underground-drain map, waterproofing design, or drainage-engineering plan." },
      { heading: "When specialist input may help", body: "Active entry, movement, repeated ponding, significant erosion, damaged drainage components, or structural concerns may warrant evaluation by a drainage, roofing, foundation, or engineering professional as appropriate." },
    ],
    takeaway: "Visible drainage clues are useful context, but source confirmation and repair design may need focused expertise.",
    related: ["visible-and-accessible-conditions", "water-heater-basics", "what-to-do-after-the-inspection"],
    cta: { label: "See the Site and Exterior Scope", path: "/services/" },
  }),
  article({
    slug: "water-heater-basics",
    category: "Systems and maintenance context",
    title: "Water Heater Basics",
    summary: "A home inspection can document visible water-heater equipment, connections, relief components, restraint, drainage, and apparent condition. It cannot see inside the tank or predict the exact failure date.",
    intro: "Water heaters combine water, energy, temperature, pressure, and location-specific installation details. The inspection records visible context and recommends qualified follow-up when the observation needs more than a visual review.",
    sections: [
      { heading: "Common visible components", body: "The report may identify the equipment type, fuel or electrical connection, location, accessible label, visible piping, shutoff, and general exterior condition." },
      { heading: "Venting and energy connections", body: "Fuel-fired and electric equipment have different visible connection and venting considerations. The inspector does not perform combustion analysis, electrical load calculations, or utility clearance." },
      { heading: "Temperature and pressure relief components", body: "Accessible relief valves and discharge piping are visually reviewed for apparent installation and condition. Do not test, cap, alter, or discharge a relief valve without appropriate training and authorization." },
      { heading: "Restraint and drainage observations", body: "Visible seismic restraint, drain pans, and drainage provisions may be documented where present. The service is not a complete code or permit certification." },
      { heading: "Corrosion, leakage, and labels", body: "Visible corrosion, moisture, staining, damage, and manufacturer data can support an observation. Label-based age is reported only when the information is accessible and reasonably reliable." },
      { heading: "Why remaining life cannot be predicted", body: "Internal tank condition, water chemistry, installation history, use, maintenance, and sudden failures are not fully visible. An apparently operating unit can still fail later." },
      { heading: "Use qualified help for adjustment or repair", body: "Gas, electricity, hot water, combustion, venting, and pressure can create serious hazards. Do not use a general educational guide as repair instructions." },
    ],
    takeaway: "Visible condition can guide questions, but internal condition and future performance remain uncertain.",
    related: ["electrical-safety-basics", "visible-and-accessible-conditions", "what-to-do-after-the-inspection"],
    cta: { label: "Review the Water-Heater Scope", path: "/services/" },
  }),
  article({
    slug: "electrical-safety-basics",
    category: "Systems and maintenance context",
    title: "Electrical Safety Basics",
    summary: "A home inspection observes accessible service equipment, panels, representative controls, protection, and visible wiring conditions. It is not a complete code certification, circuit trace, or load analysis.",
    intro: "Electrical systems contain energized components and concealed conductors. The inspector uses safe visual methods and normal controls without turning the visit into electrical service or repair work.",
    sections: [
      { heading: "Service and panel overview", body: "The inspection may identify visible service equipment, main panels, accessible subpanels, disconnects, and general conditions. Covers are removed only when the agreement, access, and safety conditions permit." },
      { heading: "Breakers, fuses, and visible wiring", body: "Accessible overcurrent devices and conductors may be observed for apparent damage, unsuitable conditions, or labeling context. The inspector does not trace every circuit or dismantle equipment." },
      { heading: "Grounding and bonding observations", body: "Visible grounding and bonding components can be documented, but concealed paths and full system effectiveness require focused electrical evaluation." },
      { heading: "GFCI and AFCI context", body: "Readily accessible protective devices may be operated within the inspection scope. The presence, absence, or response of a tested device is not a full code-compliance determination." },
      { heading: "Smoke and carbon-monoxide alarms", body: "Presence and accessible basic observations may be included where the agreement and standard apply. The inspection does not guarantee alarm age, placement compliance, sensor condition, or future operation." },
      { heading: "Not a full code or load analysis", body: "The inspection does not certify current or historic code compliance, calculate loads, verify every conductor, test concealed wiring, or evaluate all specialty and low-voltage systems." },
      { heading: "When to involve an electrical contractor", body: "Damage, overheating evidence, unsafe access, abnormal operation, unprotected openings, unsuitable components, or other material concerns may warrant prompt evaluation by an appropriately licensed electrical contractor." },
    ],
    takeaway: "Electrical observations support informed follow-up; they are not DIY instructions or a full electrical study.",
    related: ["water-heater-basics", "visible-and-accessible-conditions", "what-to-do-after-the-inspection"],
    cta: { label: "Review the Electrical Scope", path: "/services/" },
  }),
  article({
    slug: "what-to-do-after-the-inspection",
    category: "After the inspection",
    title: "What to Do After the Inspection",
    summary: "Use the full report to clarify observations, identify specialist needs, obtain independent advice, and build a practical maintenance plan. Keep the inspection separate from prohibited C&G repair work.",
    intro: "The inspection does not make the transaction decision. It gives you a property-specific record that can support better questions with the inspector, advisers, and independent qualified providers.",
    sections: [
      { heading: "Read the full report", body: "Do not rely only on the summary or a forwarded list. Read the photographs, system context, limitations, maintenance notes, and recommendations attached to each relevant observation." },
      { heading: "Ask for clarification", body: "Contact the inspector with the report section, location, photograph, and wording you want explained. Clarification should stay connected to what was observed on the inspection day." },
      { heading: "Discuss transaction choices with advisers", body: "Purchase, sale, disclosure, negotiation, financing, insurance, and legal decisions belong with the appropriate transaction, financial, and legal professionals." },
      { heading: "Obtain recommended specialist evaluations", body: "A focused evaluation may be needed when the report identifies structural, electrical, plumbing, roofing, HVAC, pest, environmental, or other questions outside the inspection scope." },
      { heading: "Request independent written estimates", body: "A repair estimate should describe scope, assumptions, exclusions, licensing, permits, materials, and timing. Do not treat the inspection report as construction plans or a contractor bid." },
      { heading: "Separate urgent concerns from maintenance", body: "Some observations may deserve prompt safety or damage-control action; others belong in routine or long-term planning. Ask qualified providers to help when prioritization depends on specialist expertise." },
      { heading: "Keep the report as a home reference", body: "The report can help organize maintenance questions and future evaluations. Remember that conditions change and later events or repairs can make observations outdated." },
      { heading: "Respect the 12-month separation", body: "C&G Contracting Services cannot offer or perform repairs on a property for which C&G prepared a home inspection report during the previous 12 months. Use independent contractors during that period." },
    ],
    takeaway: "Use the report to ask better questions, obtain qualified input, and plan independently.",
    related: ["how-to-read-a-home-inspection-report", "questions-to-ask-your-inspector", "pre-listing-inspection-guide"],
    cta: { label: "Ask a Report Question", path: "/contact/" },
  }),
];

export const resourceBySlug = new Map(resourceArticles.map((resource) => [resource.slug, resource]));

export const resourceGroups = [
  "Before the inspection",
  "Understanding the report",
  "Systems and maintenance context",
  "After the inspection",
].map((category) => ({ category, resources: resourceArticles.filter((resource) => resource.category === category) }));

export const readingMinutes = (resource) => {
  const words = [resource.intro, resource.takeaway, ...resource.sections.flatMap((section) => [section.heading, section.body]), ...(resource.checklist || [])]
    .join(" ")
    .trim()
    .split(/\s+/).length;
  return Math.max(1, Math.ceil(words / 220));
};
